### ISSUE TITLE
clj-kondo support

### ISSUE THREAD

**Issue by owenRiddy** [typedclojure/typedclojure#123]
Hey again! My experimental namespace is working now but it is a sea of linter errors.

* Does Typed Clojure support using [clj-kondo](https://github.com/clj-kondo/clj-kondo)? I've had a look and I can't see anything, but there are a lot of namespaces and maybe I missed some project outside this repo. 

* If I happened  to write basic linter rules for things like `t/defn` is there any appetite for incorporating them into Typed Clojure proper?

**Comment by frenchy64** [comment]
No support yet. Do you mean using clj-kondo annotations for type checking?

Yes, I'll accept linter rules.

**Comment by frenchy64** [comment]
Added support for most macros. Could you try version `1.1.6-20231105.040028-14` and confirm I've added the right file to the jar, and also let me know if I missed any important macros?

**Comment by owenRiddy** [comment]
Looks good to me, I have a (lein) project with dependencies: 

```
[org.typedclojure/typed.clj.checker "1.1.6-20231105.040028-14"]
[org.typedclojure/typed.clj.runtime "1.1.6-20231105.040028-14"]
```

that got rid of all the false-positive linter errors but still gave useful feedback. Big improvement, thanks.
