### ISSUE TITLE
Confusing Documentation of Types

### ISSUE THREAD

**Issue by owenRiddy** [typedclojure/typedclojure#49]
# Setup
1) Start at https://github.com/clojure/core.typed.
2) View the readme, move to https://github.com/typedclojure/typedclojure for Clojure 1.11.1 support.
3) Note typedclojure has no wiki and the README directs to core.typed.
4) There seems to have been major changes to how types are represented between the two projects - core.typed uses `def`s documented in the [API Docs](https://clojure.github.io/core.typed). typedclojure is doing some sort of magic where the types are no longer documented and only seem to exist as fleeting ghosts in the type checker.

# Problem

1) How do I list what types are supported?
2) How do I tell what has changed between core.typed and typedclojure?
3) Is there any wiki-style documentation for typedclojure? Or planned to be any?

I'm trying to debug some sort of type error involving a `Ref2` and `conj`, and having to jump to the documentation of a different project (which appears to be obsolete and work differently to typedclojure) is extremely unsettling.

**Comment by frenchy64** [comment]
I'm working on the solution for this, ideally it will improve on core.typed. Most of what I'll suggest below are temporary workarounds.

> typedclojure is doing some sort of magic where the types are no longer documented and only seem to exist as fleeting ghosts in the type checker.

Vars are no longer interned for type aliases. This was very convenient but introduced unnecessary coupling.

This was changed in [1.0.20](https://github.com/typedclojure/typedclojure/blob/main/CHANGELOG.md#1020). See that link for how to revert this change via JVM options to get back the core.typed behavior.

> How do I list what types are supported?

Apparently `clojure.core.typed/envs` is broken so there's no good answer right now.

Built-in aliases are browsable from the source [here](https://github.com/typedclojure/typedclojure/blob/main/typed/lib.clojure/src/typed/ann/clojure.cljc).

> How do I tell what has changed between core.typed and typedclojure?

Beyond [UPGRADING.md](https://github.com/typedclojure/typedclojure/blob/main/UPGRADING.md) you can also grep for `Breaking` in [CHANGELOG.md](https://github.com/typedclojure/typedclojure/blob/main/CHANGELOG.md).

I'm not aware of any users of core.typed beyond those referring to old documentation, so I haven't been putting special effort into this area for several years. I'll probably write new documentation without mentioning core.typed from here.

> Is there any wiki-style documentation for typedclojure? Or planned to be any?

Nothing I can point you to. Research and implementation have been my focus since the fork, but fortunately that's converging to where I want it. The [example projects](https://github.com/typedclojure/typedclojure/tree/main/example-projects) are the only comparable thing.

I can probably just copy a lot of the core.typed wiki here and make a few changes. Most of the documentation on how types work has not changed. I should also delete references to any old docs as it's usually just confusing.

**Comment by owenRiddy** [comment]
Thanks very much for that, it will sort me out. FWIW, feedback on the new user experience for me so far:

1. Awesome! A library for static typing.
2. Ow, clojure.core isn't fully annotated.
3. Hmm, the documentation isn't current on what the state of play is.

Probably nothing there is news, but those are the big items.

**Comment by frenchy64** [comment]
@owenRiddy thanks, that's valuable feedback. Thanks for trying it out.

**Comment by owenRiddy** [comment]
So I can't tell if the problem is me (deciphering how to set setting system properties with deps is painful :/) but as far as I can tell `envs` is still broken:

```
$ cat deps.edn
{:deps {org.clojure/clojure {:mvn/version "1.11.1"}
        org.typedclojure/typed.clj.runtime {:mvn/version "1.0.28"}
        org.typedclojure/typed.clj.checker {:mvn/version "1.0.28"}
        org.typedclojure/typed.clj.analyzer {:mvn/version "1.0.28"}}
 }
$ clj -J-Dclojure.core.typed.special-vars=true
Clojure 1.11.1
(System/getProperty "clojure.core.typed.special-vars")
"true"

(require 'clojure.core.typed)
nil

(doc clojure.core.typed/Any)
-------------------------
clojure.core.typed/Any
  Any
  Any is the top type that contains all possible values.
nil

(clojure.core.typed/envs)
Registering annotations from typed.ann.clojure...
Execution error (AssertionError) at typed.cljc.runtime.env/checker-or-nil (env.cljc:13).
Assert failed: (or (instance? clojure.lang.IAtom %) (nil? %))
```

**Comment by frenchy64** [comment]
Please try 1.0.29-SNAPSHOT once this deploys https://github.com/typedclojure/typedclojure/commit/14306c5d7c91ea7b947ec26bd1e2e5c326917516

**Comment by frenchy64** [comment]
For deps, I believe you need to create a new profile with `:jvm-opts ["-Dclojure.core.typed.special-vars=true"]` and then activate that profile.

**Comment by owenRiddy** [comment]
I switched the versions to "1.0.29-SNAPSHOT" in `deps.edn` & cleared out any caches I could find.

```
$ clj -J-Dclojure.core.typed.special-vars=true
Clojure 1.11.1
(do (require 'clojure.core.typed) (clojure.core.typed/envs))
Registering annotations from typed.ann.clojure...
Execution error (ExceptionInfo) at clojure.core.typed.errors/int-error (errors.cljc:48).
Internal Error (typed/cljc/checker/cs_rep.clj:110:18) Cannot resolve type: U
Hint: Is U in scope in namespace `typed.cljc.checker.cs-rep`?
```

**Comment by frenchy64** [comment]
Doh, forgot to commit that https://github.com/typedclojure/typedclojure/commit/79e613d865ed1b5c1c041f57a82229927d9429bb

**Comment by owenRiddy** [comment]
```
$ clj -J-Dclojure.core.typed.special-vars=true
Clojure 1.11.1
(do (require 'clojure.core.typed 'clojure.pprint) (clojure.pprint/pprint (clojure.core.typed/envs)))
Registering annotations from typed.ann.clojure...
{:aliases
 {typed.cljc.checker.frees/VarianceMap
  (typed.clojure/Map
   typed.clojure/Sym
   typed.cljc.checker.type-rep/Variance),
  typed.clojure/NilableNonEmptyASeq
  (typed.clojure/TFn
   [[x :variance :covariant]]
   (typed.clojure/Nilable (typed.clojure/NonEmptyASeq x))),
  typed.clojure/UUID java.util.UUID,
<continues>
```

Looks good to me, thankyou again Ambrose.

**Comment by frenchy64** [comment]
Thanks for checking, releasing 1.0.29 with this fix https://github.com/typedclojure/typedclojure/commit/44cf83d17eb2ceb64003c59d700524aa038f1c65

**Comment by frenchy64** [comment]
@owenRiddy There's a new macro in 1.0.30 called t/doc-clj that IMO is better than anything core.typed provided.

```clojure
typed.dev=> (doc t/doc-clj)
-------------------------
typed.clojure/doc-clj
([syn])
Macro
  Pass any syntax fragment related to Typed Clojure to print documentation on it.
  eg., (doc-clj t/Rec)
       (doc-clj '[])
       (doc-clj +) ;; print var annotation
       (doc-clj MyAlias) ;; print defalias mapping

  Use :doc/index for documentation index.
typed.dev=> (t/doc-clj t/Transducer)
Registering annotations from typed.ann.clojure...
Registering annotations from typed.lib.clojure.core.async...
Type alias typed.clojure/Transducer
(t/TFn
 [[in :variance :contravariant] [out :variance :covariant]]
 (t/All [r] [(t/Reducer out r) -> (t/Reducer in r)]))
Metadata:
{:doc "A transducer function that transforms in to out.",
 :forms '[(Transducer in out)],
 :file "typed/ann/clojure.cljc"}

nil
typed.dev=> (t/doc-clj :doc/index)
Documentation index
 :doc/{type-}syntax   An overview of the syntax for types.
 :doc/filter-syntax   An overview of the syntax for propositions.
 :doc/object-syntax   An overview of the syntax for symbolic objects.
 :doc/meta{data}   How to use use metadata to annotate expressions.

nil
typed.dev=> (t/doc-clj :doc/syntax)
Type syntax overview

nil, true, false, are shorthand for t/Val.

Quoted booleans, nil, keywords, symbols and numbers are shorthand for t/Val.

Lists (T1 T2 T3) are type function applications. See t/TFn.

Vectors like [T1 :-> T2] stand for function types. See t/IFn.

Quoted vectors like '[T1 T2] stand for heterogenous vector types. See t/HVec.

Quoted maps like '{:k1 T1 :k2 T2} stand for heterogenous map types. See t/HMap.

A set of special primitive types are identified by qualified symbols.
Some are used in a list like (t/Val 1), others stand alone like t/AnyValue.
See :doc/specials for the full list.

Non-special symbols resolve to type aliases defined by t/defalias or platform-specific types
like classes.
nil
typed.dev=> (t/doc-clj '[])
Special type: typed.clojure/HVec
HVec is a type for heterogeneous vectors.
                  It extends typed.clojure/Vec and is a subtype
                  of typed.clojure/HSequential.
Forms: [(HVec [fixed*] :filter-sets [FS*] :objects [obj*]) (HVec [fixed* type :*] :filter-sets [FS*] :objects [obj*]) (HVec [fixed* type :.. bound] :filter-sets [FS*] :objects [obj*]) (quote [fixed*]) (quote [fixed* type :*]) (quote [fixed* type :.. bound])]

nil
typed.dev=> (t/doc-clj +)
Printing the annotation for var clojure.core/+ (see typed.clojure/TypeOf for usage in type syntax)
(t/IFn
 [Long * -> Long]
 [(t/U Long Double) * -> Double]
 [t/AnyInteger * -> t/AnyInteger]
 [t/Num * -> t/Num])

nil
```

**Comment by owenRiddy** [comment]
I was away from my Github credentials for a little bit and then this got lost in my inbox - but I have come back to it to say thanks. This does look helpful.
